[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "token_gate"

[dependencies]
fungible_token_abi = { path = "../fungible_token_abi"}
# TODO: use implicit std when new forc is released (> 0.16.2)
std = { path = "../../sway/sway-lib-std" }
