name: CI

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  RUST_VERSION: 1.61.0

jobs:
  lint-toml-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - name: Install Cargo.toml linter
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-toml-lint
          version: '0.1'
      - name: Run Cargo.toml linter
        run: git ls-files | grep Cargo.toml$ | xargs --verbose -n 1 cargo-toml-lint

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [
          'fungible_token_abi',
          'L2ERC20Gateway_abi',
          'L2ERC20Gateway_caller_script',
          'message_to_fungible_token_predicate', 
          'POC/test_predicate',
          'POC/test_script'
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true

      - name: Init cache
        uses: Swatinem/rust-cache@v1

      - name: Install a modern linker (mold)
        uses: rui314/setup-mold@v1

      - name: Force Rust to use mold globally for compilation
        run: |
          touch ~/.cargo/config.toml
          echo "[target.x86_64-unknown-linux-gnu]" > ~/.cargo/config.toml
          echo 'linker = "clang"' >> ~/.cargo/config.toml
          echo 'rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]' >> ~/.cargo/config.toml

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Install Fuel toolchain
        uses: FuelLabs/action-fuel-toolchain@v0.1.0

      - name: Check Sway formatting
        run: forc fmt --path ${{ matrix.project }} --check

      - name: Build Sway
        run: forc build --path ${{ matrix.project }}

       - name: Check Rust formatting
        run: |
          if [ ${{ matrix.project }} = 'POC/script' ]; then
          cd ${{ matrix.project }}
          cargo fmt --verbose --check

      - name: Run Forc tests
        run: |
          if [ ${{ matrix.project }} = 'POC/script' ]; then
          cd ${{ matrix.project }}
          forc test
